--- # display host name in playbook
- hosts: agent.abc.com
  user: root
  tasks:
      - name: "{{inventory_hostname}}"
        debug: msg="{{inventory_hostname}}"
      - name: hostname "{{ansible_hostname}}"
        debug: msg="{{ansible_hostname}}" 
      - include: loops.yml  
