--- # loops for creating packages
- hosts: server
  user: user1
  sudo: yes
  gather_facts: yes
  connection: ssh
  tasks:
   - name: installing packages
     yum: name={{item}} state=installed
     with_items:
       - lynx
       - curl
       - wget
