--- # pause module
- hosts: server
  user: user1
  sudo: yes
  gather_facts: yes
  tasks:
   - name: Install telenet and lynx package
     yum: name:{{item}} state=latest
     with_items:
          - telnet
          - lynx
   - name: pause
     pause:
        prompt: press enter to cont
   - name: verify the installation
     raw: yum list installed > grep telnet > /home/user1/play.log
