--- # register
- hosts: server
  user: user1
  sudo: yes
  gather_facts: yes
  tasks:
   - name: install httpd
     yum: name=httpd state=installed
   - name: verify the status
#     service: name=httpd state=started
     command: service httpd start
     register: result
   - debug: var=result
